use serde::{Deserialize, Serialize};

/// Represents the category of threat detected in a message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ThreatType {
    /// No threat detected.
    #[default]
    None,
    /// Bullying or harassment behaviour.
    Bullying,
    /// Child grooming behaviour.
    Grooming,
    /// Sexually explicit content.
    Explicit,
    /// Direct threat of violence or harm.
    Threat,
    /// Self-harm or suicidal ideation signals.
    SelfHarm,
    /// Unsolicited bulk or promotional messaging.
    Spam,
    /// Fraudulent or deceptive scheme.
    Scam,
    /// Credential or identity theft attempt via links.
    Phishing,
    /// Psychological manipulation or coercion.
    Manipulation,
    /// Not-safe-for-work media content.
    Nsfw,
    /// Hate speech targeting protected groups.
    HateSpeech,
    /// Disclosure of someone's private information.
    Doxxing,
    /// Personally identifiable information leakage.
    PiiLeakage,
    /// Propaganda or disinformation content.
    Propaganda,
    /// OPSEC violation — leaking military operational information.
    OpsecViolation,
    /// Enemy psychological operations targeting the user.
    Psyops,
    /// Social engineering attempt targeting military personnel.
    MilitarySocialEng,
    /// Geographic coordinate or location leak in military context.
    CoordinateLeak,
}

/// Represents the confidence level of a detection result.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum Confidence {
    /// Low confidence; signal may be a false positive.
    #[default]
    Low,
    /// Moderate confidence in the detection.
    Medium,
    /// High confidence in the detection.
    High,
}

/// Represents the protection strictness level configured by the user or policy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ProtectionLevel {
    /// Protection is disabled.
    Off,
    /// Minimal filtering; only high-confidence threats are acted on.
    Low,
    /// Balanced filtering suitable for most users.
    #[default]
    Medium,
    /// Strict filtering; used for child accounts.
    High,
}

/// Represents the age category of the account holder.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum AccountType {
    /// User aged 18 or older.
    #[default]
    Adult,
    /// User aged 13-17.
    Teen,
    /// User aged under 13.
    Child,
}

/// Represents the type of conversation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ConversationType {
    /// One-to-one direct message.
    #[default]
    Direct,
    /// Group conversation with multiple participants.
    Group,
}

/// Represents the analysis layer that produced a detection signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum DetectionLayer {
    /// Signal generated by keyword and regex pattern matching.
    #[default]
    PatternMatching,
    /// Signal generated by ML model inference.
    MlClassification,
    /// Signal generated by domain-specific heuristics.
    DomainHeuristic,
    /// Signal generated by conversation-level context analysis.
    ContextAnalysis,
    /// Signal generated by relay-side inference.
    RelayInference,
}
