//! Core domain types for the AURA analysis engine.

use serde::{Deserialize, Serialize};

use crate::ids::{ConversationId, SenderId};

/// Represents the category of threat detected in a message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ThreatType {
    /// No threat detected.
    None,
    /// Bullying or harassment behaviour.
    Bullying,
    /// Child grooming behaviour.
    Grooming,
    /// Sexually explicit content.
    Explicit,
    /// Direct threat of violence or harm.
    Threat,
    /// Self-harm or suicidal ideation signals.
    SelfHarm,
    /// Unsolicited bulk or promotional messaging.
    Spam,
    /// Fraudulent or deceptive scheme.
    Scam,
    /// Credential or identity theft attempt via links.
    Phishing,
    /// Psychological manipulation or coercion.
    Manipulation,
    /// Not-safe-for-work media content.
    Nsfw,
    /// Hate speech targeting protected groups.
    HateSpeech,
    /// Disclosure of someone's private information.
    Doxxing,
    /// Personally identifiable information leakage.
    PiiLeakage,
}

/// Represents the confidence level of a detection result.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Confidence {
    /// Low confidence; signal may be a false positive.
    Low,
    /// Moderate confidence in the detection.
    Medium,
    /// High confidence in the detection.
    High,
}

/// Represents the enforcement action to apply to a message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Action {
    /// Allows the message through without modification.
    Allow,
    /// Marks the message for review but still delivers it.
    Mark,
    /// Blurs or hides the message content until the user opts in.
    Blur,
    /// Displays a warning to the recipient before showing the message.
    Warn,
    /// Blocks the message from being delivered.
    Block,
}

/// Represents the protection strictness level configured by the user or policy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ProtectionLevel {
    /// Protection is disabled.
    Off,
    /// Minimal filtering; only high-confidence threats are acted on.
    Low,
    /// Balanced filtering suitable for most users.
    #[default]
    Medium,
    /// Strict filtering; used for child accounts.
    High,
}

/// Represents the age category of the account holder.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AccountType {
    /// User aged 18 or older.
    Adult,
    /// User aged 13-17.
    Teen,
    /// User aged under 13.
    Child,
}

/// Represents the analysis layer that produced a detection signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DetectionLayer {
    /// Signal generated by keyword and regex pattern matching.
    PatternMatching,
    /// Signal generated by ML model inference.
    MlClassification,
    /// Signal generated by conversation-level context analysis.
    ContextAnalysis,
}

/// Represents the broad family a detection signal belongs to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum SignalFamily {
    /// Signal derived from message text or media content.
    #[default]
    Content,
    /// Signal derived from conversation-level patterns.
    Conversation,
    /// Signal derived from URL or link analysis.
    Link,
    /// Signal derived from abusive messaging behaviour.
    Abuse,
}

/// Represents a user-facing action the client UI should perform.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UiAction {
    /// Shows a warning dialog before the user sends a message.
    WarnBeforeSend,
    /// Shows a warning before displaying received content.
    WarnBeforeDisplay,
    /// Blurs content until the user explicitly taps to reveal.
    BlurUntilTap,
    /// Asks for confirmation before opening a link.
    ConfirmBeforeOpenLink,
    /// Suggests blocking the contact.
    SuggestBlockContact,
    /// Suggests reporting the contact or message.
    SuggestReport,
    /// Restricts interactions with unknown contacts.
    RestrictUnknownContact,
    /// Introduces a delay to slow down a rapid conversation.
    SlowDownConversation,
    /// Displays crisis support resources (hotlines, links).
    ShowCrisisSupport,
    /// Escalates the situation to a guardian or parent.
    EscalateToGuardian,
}

/// Represents the trust tier of a contact based on interaction history.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum CircleTier {
    /// Close, frequently interacted contact.
    Inner,
    /// Known contact with moderate interaction history.
    Regular,
    /// Infrequently contacted person.
    Occasional,
    /// Recently added or unknown contact.
    #[default]
    New,
}

/// Represents the behavioural trend of a contact over time.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum BehavioralTrend {
    /// Behaviour is consistent and within normal bounds.
    #[default]
    Stable,
    /// Behaviour is trending toward safer interactions.
    Improving,
    /// Behaviour is slowly deteriorating.
    GradualWorsening,
    /// Behaviour is rapidly deteriorating.
    RapidWorsening,
    /// Roles in the conversation have inverted (e.g. victim becomes aggressor).
    RoleReversal,
}

/// Holds a single detection signal produced by one analysis layer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectionSignal {
    #[serde(default)]
    pub reason_code: String,
    pub explanation: String,
    pub score: f32,
    pub threat_type: ThreatType,
    pub confidence: Confidence,
    pub layer: DetectionLayer,
    #[serde(default)]
    pub family: SignalFamily,
}

impl DetectionSignal {
    /// Creates a signal originating from the pattern-matching layer.
    pub fn pattern(
        threat_type: ThreatType,
        score: f32,
        confidence: Confidence,
        reason_code: impl Into<String>,
        explanation: impl Into<String>,
    ) -> Self {
        let family = match threat_type {
            ThreatType::Phishing => SignalFamily::Link,
            ThreatType::Spam | ThreatType::Scam => SignalFamily::Abuse,
            ThreatType::None
            | ThreatType::Bullying
            | ThreatType::Grooming
            | ThreatType::Explicit
            | ThreatType::Threat
            | ThreatType::SelfHarm
            | ThreatType::Manipulation
            | ThreatType::Nsfw
            | ThreatType::HateSpeech
            | ThreatType::Doxxing
            | ThreatType::PiiLeakage => SignalFamily::Content,
        };

        Self {
            threat_type,
            score,
            confidence,
            layer: DetectionLayer::PatternMatching,
            family,
            reason_code: reason_code.into(),
            explanation: explanation.into(),
        }
    }

    /// Creates a signal originating from the ML classification layer.
    pub fn ml(
        threat_type: ThreatType,
        score: f32,
        confidence: Confidence,
        reason_code: impl Into<String>,
        explanation: impl Into<String>,
    ) -> Self {
        Self {
            threat_type,
            score,
            confidence,
            layer: DetectionLayer::MlClassification,
            family: SignalFamily::Content,
            reason_code: reason_code.into(),
            explanation: explanation.into(),
        }
    }

    /// Creates a signal originating from the context analysis layer.
    pub fn context(
        threat_type: ThreatType,
        score: f32,
        confidence: Confidence,
        family: SignalFamily,
        reason_code: impl Into<String>,
        explanation: impl Into<String>,
    ) -> Self {
        Self {
            threat_type,
            score,
            confidence,
            layer: DetectionLayer::ContextAnalysis,
            family,
            reason_code: reason_code.into(),
            explanation: explanation.into(),
        }
    }
}

/// Holds per-family risk scores that compose the overall risk assessment.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct RiskBreakdown {
    pub content: f32,
    pub conversation: f32,
    pub link: f32,
    pub abuse: f32,
}

/// Represents the level of uncertainty in an inference result.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum UncertaintyLevel {
    /// Inference has high certainty.
    Low,
    /// Inference has moderate certainty.
    #[default]
    Medium,
    /// Inference has low certainty; result should be treated cautiously.
    High,
}

/// Represents the time horizon over which a risk is expected to materialise.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum RiskHorizon {
    /// Risk horizon cannot be determined.
    #[default]
    Unknown,
    /// Risk may materialise within minutes to hours.
    Immediate,
    /// Risk may materialise within hours to days.
    ShortTerm,
    /// Risk is ongoing and persistent.
    Sustained,
}

/// Represents a category of latent psychological state observed in a conversation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LatentStateKind {
    /// One party is building emotional dependency on the other.
    DependencyBuilding,
    /// One party is pressuring the other to cut off outside contacts.
    IsolationPressure,
    /// One party exerts controlling behaviour over the other.
    CoerciveControl,
    /// One party is humiliating or degrading the other.
    Humiliation,
    /// One party shows signs of crisis-level vulnerability.
    CrisisVulnerability,
    /// Protective or supportive dynamics are present in the conversation.
    ProtectiveSupport,
    /// Escalation dynamics within a group conversation.
    GroupEscalation,
}

/// Holds evidence for a single latent psychological state.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LatentStateEvidence {
    pub kind: LatentStateKind,
    pub score: f32,
    #[serde(default)]
    pub reason_codes: Vec<String>,
}

/// Holds psychological inference output for a conversation. This is intentionally
/// domain-only and does not define the external protobuf contract.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct InferenceSummary {
    pub uncertainty: UncertaintyLevel,
    pub risk_horizon: RiskHorizon,
    pub escalation_likelihood_24h: f32,
    pub protective_factor_strength: f32,
    #[serde(default)]
    pub latent_states: Vec<LatentStateEvidence>,
}

/// Holds a point-in-time snapshot of a contact's trust and behavioural profile.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContactSnapshot {
    pub sender_id: SenderId,
    pub rating: f32,
    pub trust_level: f32,
    pub circle_tier: CircleTier,
    pub trend: BehavioralTrend,
    pub is_trusted: bool,
    pub is_new_contact: bool,
    pub first_seen_ms: u64,
    pub last_seen_ms: u64,
    pub conversation_count: usize,
}

/// Holds the complete result of analysing a single message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisResult {
    pub threat_type: ThreatType,
    pub confidence: Confidence,
    pub action: Action,
    pub score: f32,
    pub explanation: String,
    pub detected_threats: Vec<(ThreatType, f32)>,
    pub signals: Vec<DetectionSignal>,
    pub recommended_action: Option<ActionRecommendation>,
    #[serde(default)]
    pub risk_breakdown: RiskBreakdown,
    #[serde(default)]
    pub contact_snapshot: Option<ContactSnapshot>,
    #[serde(default)]
    pub reason_codes: Vec<String>,
    #[serde(default)]
    pub inference: InferenceSummary,
    pub analysis_time_us: u64,
}

impl AnalysisResult {
    /// Creates a clean (no-threat) result with the given analysis duration.
    pub fn clean(analysis_time_us: u64) -> Self {
        Self {
            threat_type: ThreatType::None,
            confidence: Confidence::Low,
            action: Action::Allow,
            score: 0.0,
            explanation: String::new(),
            detected_threats: Vec::new(),
            signals: Vec::new(),
            recommended_action: None,
            risk_breakdown: RiskBreakdown::default(),
            contact_snapshot: None,
            reason_codes: Vec::new(),
            inference: InferenceSummary::default(),
            analysis_time_us,
        }
    }

    /// Returns `true` if any threat was detected.
    pub fn is_threat(&self) -> bool {
        self.threat_type != ThreatType::None
    }

    /// Returns `true` if crisis support resources should be shown to the user.
    pub fn needs_crisis_resources(&self) -> bool {
        self.threat_type == ThreatType::SelfHarm
    }
}

/// Represents the priority level of a parent or guardian alert.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AlertPriority {
    /// No alert required.
    None,
    /// Low-priority informational alert.
    Low,
    /// Medium-priority alert requiring attention.
    Medium,
    /// High-priority alert requiring prompt action.
    High,
    /// Urgent alert requiring immediate action.
    Urgent,
}

/// Represents a recommended follow-up action after a threat is detected.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FollowUpAction {
    /// Continues monitoring the conversation for further signals.
    MonitorConversation,
    /// Suggests blocking the contact to the user.
    BlockSuggested,
    /// Suggests reviewing the contact's full profile.
    ReviewContactProfile,
    /// Recommends reporting the situation to authorities.
    ReportToAuthorities,
}

/// Holds the full set of recommended actions for a detected threat.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActionRecommendation {
    pub parent_alert: AlertPriority,
    pub follow_ups: Vec<FollowUpAction>,
    pub crisis_resources: bool,
    #[serde(default)]
    pub ui_actions: Vec<UiAction>,
    #[serde(default)]
    pub reason_codes: Vec<String>,
}

/// Represents the type of conversation a message belongs to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ConversationType {
    /// One-to-one direct message.
    #[default]
    Direct,
    /// Group chat conversation (legacy variant).
    GroupChat,
    /// Group conversation.
    Group,
}

/// Controls detection strictness for enrichment and grooming analysis.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AnalysisMode {
    /// Standard detection thresholds.
    Standard,
    /// Stricter detection thresholds for higher-risk accounts.
    Strict,
}

impl AnalysisMode {
    /// Returns true if this mode uses strict detection thresholds.
    pub fn is_strict(self) -> bool {
        match self {
            AnalysisMode::Standard => false,
            AnalysisMode::Strict => true,
        }
    }
}

/// Represents the media type of a message's content.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContentType {
    /// Plain text message.
    Text,
    /// Image attachment.
    Image,
    /// Voice or audio message.
    Voice,
    /// Video attachment.
    Video,
    /// URL or link-only message.
    Url,
}

/// Holds the raw input data for a single message to be analysed.
#[derive(Debug, Clone)]
pub struct MessageInput {
    pub content_type: ContentType,
    pub text: Option<String>,
    pub image_data: Option<Vec<u8>>,
    pub sender_id: SenderId,
    pub conversation_id: ConversationId,
    pub language: Option<String>,
    pub conversation_type: ConversationType,
    pub member_count: Option<u32>,
}
