//! Core domain types for the AURA analysis engine.
//!
//! Canonical shared enums (`ThreatType`, `Confidence`, `ProtectionLevel`,
//! `AccountType`, `ConversationType`) live in `aura-contracts` and are exposed
//! here as part of the core domain API.

use serde::{Deserialize, Serialize};

use crate::ids::{ConversationId, SenderId};

// ── Canonical shared enums (source: aura-contracts) ─────────────────
pub use aura_contracts::{
    AccountType, Confidence, ProtectionLevel, RelationshipTrustSource, SenderRelationship,
    ThreatType,
};

/// Represents the enforcement action to apply to a message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Action {
    /// Allows the message through without modification.
    Allow,
    /// Marks the message for review but still delivers it.
    Mark,
    /// Blurs or hides the message content until the user opts in.
    Blur,
    /// Displays a warning to the recipient before showing the message.
    Warn,
    /// Blocks the message from being delivered.
    Block,
}

/// Account-level domain mode selection that runs on top of base Aura.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum DomainMode {
    /// Base Aura only (no domain extension).
    #[default]
    None,
    /// Enables the Kids domain extension.
    Kids,
    /// Enables the Military domain extension.
    Military,
}

/// Selects a domain extension that runs on top of the central AURA core.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AuraDomainModule {
    /// Child and teen safety extension.
    Kids,
    /// Military safety extension.
    Military,
}

impl DomainMode {
    /// Returns the domain extension selected for this mode.
    pub fn domain_module(self) -> Option<AuraDomainModule> {
        match self {
            DomainMode::None => None,
            DomainMode::Kids => Some(AuraDomainModule::Kids),
            DomainMode::Military => Some(AuraDomainModule::Military),
        }
    }
}

/// Represents the analysis layer that produced a detection signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DetectionLayer {
    /// Signal generated by keyword and regex pattern matching.
    PatternMatching,
    /// Signal generated by ML model inference.
    MlClassification,
    /// Signal generated by conversation-level context analysis.
    ContextAnalysis,
}

/// Represents the broad family a detection signal belongs to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum SignalFamily {
    /// Signal derived from message text or media content.
    #[default]
    Content,
    /// Signal derived from conversation-level patterns.
    Conversation,
    /// Signal derived from URL or link analysis.
    Link,
    /// Signal derived from abusive messaging behaviour.
    Abuse,
}

/// Represents a user-facing action the client UI should perform.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UiAction {
    /// Shows a warning dialog before the user sends a message.
    WarnBeforeSend,
    /// Shows a warning before displaying received content.
    WarnBeforeDisplay,
    /// Blurs content until the user explicitly taps to reveal.
    BlurUntilTap,
    /// Asks for confirmation before opening a link.
    ConfirmBeforeOpenLink,
    /// Suggests blocking the contact.
    SuggestBlockContact,
    /// Suggests reporting the contact or message.
    SuggestReport,
    /// Restricts interactions with unknown contacts.
    RestrictUnknownContact,
    /// Introduces a delay to slow down a rapid conversation.
    SlowDownConversation,
    /// Displays crisis support resources (hotlines, links).
    ShowCrisisSupport,
    /// Escalates the situation to a guardian or parent.
    EscalateToGuardian,
}

/// Represents the trust tier of a contact based on interaction history.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum CircleTier {
    /// Close, frequently interacted contact.
    Inner,
    /// Known contact with moderate interaction history.
    Regular,
    /// Infrequently contacted person.
    Occasional,
    /// Recently added or unknown contact.
    #[default]
    New,
}

/// Represents the behavioural trend of a contact over time.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum BehavioralTrend {
    /// Behaviour is consistent and within normal bounds.
    #[default]
    Stable,
    /// Behaviour is trending toward safer interactions.
    Improving,
    /// Behaviour is slowly deteriorating.
    GradualWorsening,
    /// Behaviour is rapidly deteriorating.
    RapidWorsening,
    /// Roles in the conversation have inverted (e.g. victim becomes aggressor).
    RoleReversal,
}

/// Holds a single detection signal produced by one analysis layer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectionSignal {
    #[serde(default)]
    pub reason_code: String,
    pub explanation: String,
    pub score: f32,
    pub threat_type: ThreatType,
    pub confidence: Confidence,
    pub layer: DetectionLayer,
    #[serde(default)]
    pub family: SignalFamily,
    #[serde(default)]
    pub threat_subtype: String,
}

impl DetectionSignal {
    /// Creates a signal originating from the pattern-matching layer.
    pub fn pattern(
        threat_type: ThreatType,
        score: f32,
        confidence: Confidence,
        reason_code: impl Into<String>,
        explanation: impl Into<String>,
    ) -> Self {
        let family = match threat_type {
            ThreatType::Phishing | ThreatType::MilitarySocialEng => SignalFamily::Link,
            ThreatType::Spam | ThreatType::Scam | ThreatType::Psyops => SignalFamily::Abuse,
            ThreatType::Propaganda => SignalFamily::Content,
            ThreatType::OpsecViolation | ThreatType::CoordinateLeak => SignalFamily::Content,
            ThreatType::None
            | ThreatType::Bullying
            | ThreatType::Grooming
            | ThreatType::Explicit
            | ThreatType::Threat
            | ThreatType::SelfHarm
            | ThreatType::Manipulation
            | ThreatType::Nsfw
            | ThreatType::HateSpeech
            | ThreatType::Doxxing
            | ThreatType::PiiLeakage => SignalFamily::Content,
        };

        Self {
            threat_type,
            score,
            confidence,
            layer: DetectionLayer::PatternMatching,
            family,
            reason_code: reason_code.into(),
            explanation: explanation.into(),
            threat_subtype: String::new(),
        }
    }

    /// Creates a signal originating from the ML classification layer.
    pub fn ml(
        threat_type: ThreatType,
        score: f32,
        confidence: Confidence,
        reason_code: impl Into<String>,
        explanation: impl Into<String>,
    ) -> Self {
        Self {
            threat_type,
            score,
            confidence,
            layer: DetectionLayer::MlClassification,
            family: SignalFamily::Content,
            reason_code: reason_code.into(),
            explanation: explanation.into(),
            threat_subtype: String::new(),
        }
    }

    /// Creates a signal originating from the context analysis layer.
    pub fn context(
        threat_type: ThreatType,
        score: f32,
        confidence: Confidence,
        family: SignalFamily,
        reason_code: impl Into<String>,
        explanation: impl Into<String>,
    ) -> Self {
        Self {
            threat_type,
            score,
            confidence,
            layer: DetectionLayer::ContextAnalysis,
            family,
            reason_code: reason_code.into(),
            explanation: explanation.into(),
            threat_subtype: String::new(),
        }
    }

    /// Attaches a fine-grained subtype to the signal.
    pub fn with_threat_subtype(mut self, subtype: impl Into<String>) -> Self {
        self.threat_subtype = subtype.into();
        self
    }
}

/// Holds per-family risk scores that compose the overall risk assessment.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct RiskBreakdown {
    pub content: f32,
    pub conversation: f32,
    pub link: f32,
    pub abuse: f32,
}

/// Represents the level of uncertainty in an inference result.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum UncertaintyLevel {
    /// Inference has high certainty.
    Low,
    /// Inference has moderate certainty.
    #[default]
    Medium,
    /// Inference has low certainty; result should be treated cautiously.
    High,
}

/// Represents the time horizon over which a risk is expected to materialise.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum RiskHorizon {
    /// Risk horizon cannot be determined.
    #[default]
    Unknown,
    /// Risk may materialise within minutes to hours.
    Immediate,
    /// Risk may materialise within hours to days.
    ShortTerm,
    /// Risk is ongoing and persistent.
    Sustained,
}

/// Represents a category of latent psychological state observed in a conversation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LatentStateKind {
    /// One party is building emotional dependency on the other.
    DependencyBuilding,
    /// One party is pressuring the other to cut off outside contacts.
    IsolationPressure,
    /// One party exerts controlling behaviour over the other.
    CoerciveControl,
    /// One party is humiliating or degrading the other.
    Humiliation,
    /// One party shows signs of crisis-level vulnerability.
    CrisisVulnerability,
    /// Protective or supportive dynamics are present in the conversation.
    ProtectiveSupport,
    /// Escalation dynamics within a group conversation.
    GroupEscalation,
}

/// Holds evidence for a single latent psychological state.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LatentStateEvidence {
    pub kind: LatentStateKind,
    pub score: f32,
    #[serde(default)]
    pub reason_codes: Vec<String>,
}

/// Holds psychological inference output for a conversation. This is intentionally
/// domain-only and does not define the external protobuf contract.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct InferenceSummary {
    pub uncertainty: UncertaintyLevel,
    pub risk_horizon: RiskHorizon,
    pub escalation_likelihood_24h: f32,
    pub protective_factor_strength: f32,
    #[serde(default)]
    pub latent_states: Vec<LatentStateEvidence>,
}

/// Holds a point-in-time snapshot of a contact's trust and behavioural profile.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContactSnapshot {
    pub sender_id: SenderId,
    pub rating: f32,
    pub trust_level: f32,
    pub circle_tier: CircleTier,
    pub trend: BehavioralTrend,
    pub is_trusted: bool,
    pub is_new_contact: bool,
    pub first_seen_ms: u64,
    pub last_seen_ms: u64,
    pub conversation_count: usize,
    pub grooming_event_count: u64,
    pub bullying_event_count: u64,
    pub manipulation_event_count: u64,
    pub total_threat_events: u64,
}

/// Compact typed summary of the interpreter's context decision for a single message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ContextSpeechAct {
    #[default]
    Unknown,
    Assert,
    Ask,
    Quote,
    Report,
    Counter,
    Support,
    Solicit,
}

/// Compact typed summary of the interpreter's stance decision for a single message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ContextStance {
    #[default]
    Unknown,
    Endorse,
    Oppose,
    Neutral,
    Ambiguous,
}

/// Compact typed summary of how a message is directed in context.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ContextDirectionality {
    #[default]
    Unknown,
    DirectedAtUser,
    SelfReferential,
    ThirdParty,
    Broadcast,
}

/// Compact typed summary of the interaction reciprocity for a single message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ContextReciprocity {
    #[default]
    Unknown,
    OneSided,
    Mutual,
}

/// Relationship-level context attached to the interpreted message.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Default)]
pub struct ContextRelationshipSummary {
    #[serde(default)]
    pub is_new_contact: bool,
    #[serde(default)]
    pub is_trusted: bool,
    #[serde(default)]
    pub circle_tier: CircleTier,
    #[serde(default)]
    pub trust_level: f32,
    #[serde(default)]
    pub prior_conversation_count: usize,
}

/// Trajectory-level context attached to the interpreted message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct ContextTrajectorySummary {
    #[serde(default)]
    pub repeated_by_sender: bool,
    #[serde(default)]
    pub escalating: bool,
    #[serde(default)]
    pub cross_conversation: bool,
    #[serde(default)]
    pub bursty: bool,
}

/// Typed context summary used by inference, policy, and product layers.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Default)]
pub struct AnalysisContextSummary {
    #[serde(default)]
    pub speech_act: ContextSpeechAct,
    #[serde(default)]
    pub stance: ContextStance,
    #[serde(default)]
    pub directionality: ContextDirectionality,
    #[serde(default)]
    pub reciprocity: ContextReciprocity,
    #[serde(default)]
    pub relationship: ContextRelationshipSummary,
    #[serde(default)]
    pub trajectory: ContextTrajectorySummary,
    #[serde(default)]
    pub filter_applied: bool,
    #[serde(default)]
    pub confidence: f32,
}

impl AnalysisContextSummary {
    pub fn is_meaningful(&self) -> bool {
        self.speech_act != ContextSpeechAct::Unknown
            || self.stance != ContextStance::Unknown
            || self.directionality != ContextDirectionality::Unknown
            || self.reciprocity != ContextReciprocity::Unknown
            || self.relationship.is_new_contact
            || self.relationship.is_trusted
            || self.relationship.circle_tier != CircleTier::New
            || self.relationship.trust_level > 0.0
            || self.relationship.prior_conversation_count > 0
            || self.trajectory.repeated_by_sender
            || self.trajectory.escalating
            || self.trajectory.cross_conversation
            || self.trajectory.bursty
            || self.filter_applied
            || self.confidence > 0.0
    }

    pub fn has_safe_policy_context(&self) -> bool {
        matches!(
            self.speech_act,
            ContextSpeechAct::Quote
                | ContextSpeechAct::Report
                | ContextSpeechAct::Counter
                | ContextSpeechAct::Support
        ) || matches!(self.stance, ContextStance::Oppose | ContextStance::Neutral)
            || self.relationship.is_trusted
    }

    pub fn has_risky_policy_context(&self) -> bool {
        matches!(self.speech_act, ContextSpeechAct::Solicit)
            || matches!(self.stance, ContextStance::Ambiguous)
            || matches!(
                self.directionality,
                ContextDirectionality::DirectedAtUser | ContextDirectionality::SelfReferential
            )
            || self.relationship.is_new_contact
            || matches!(self.reciprocity, ContextReciprocity::OneSided)
            || self.trajectory.repeated_by_sender
            || self.trajectory.escalating
            || self.trajectory.cross_conversation
            || self.trajectory.bursty
    }

    pub fn should_soften_policy(&self) -> bool {
        self.filter_applied && self.has_safe_policy_context() && !self.has_risky_policy_context()
    }

    pub fn from_markers(context_markers: &[String]) -> Self {
        let mut summary = Self::default();
        for marker in context_markers {
            match marker.as_str() {
                "context.filter.applied" => summary.filter_applied = true,
                "context.speech_act.ask" => summary.speech_act = ContextSpeechAct::Ask,
                "context.speech_act.quote" => summary.speech_act = ContextSpeechAct::Quote,
                "context.speech_act.report" => summary.speech_act = ContextSpeechAct::Report,
                "context.speech_act.counter" => summary.speech_act = ContextSpeechAct::Counter,
                "context.speech_act.support" => summary.speech_act = ContextSpeechAct::Support,
                "context.speech_act.solicit" => summary.speech_act = ContextSpeechAct::Solicit,
                "context.stance.oppose" => summary.stance = ContextStance::Oppose,
                "context.stance.neutral" => summary.stance = ContextStance::Neutral,
                "context.stance.ambiguous" => summary.stance = ContextStance::Ambiguous,
                "context.direction.directed_at_user" => {
                    summary.directionality = ContextDirectionality::DirectedAtUser
                }
                "context.direction.self_referential" => {
                    summary.directionality = ContextDirectionality::SelfReferential
                }
                "context.direction.third_party" => {
                    summary.directionality = ContextDirectionality::ThirdParty
                }
                "context.relationship.new_contact" => summary.relationship.is_new_contact = true,
                "context.relationship.trusted" => summary.relationship.is_trusted = true,
                "context.reciprocity.one_sided" => {
                    summary.reciprocity = ContextReciprocity::OneSided
                }
                "context.trajectory.repeated_sender" => {
                    summary.trajectory.repeated_by_sender = true
                }
                "context.trajectory.escalating" => summary.trajectory.escalating = true,
                "context.trajectory.cross_conversation" => {
                    summary.trajectory.cross_conversation = true
                }
                "context.trajectory.bursty" => summary.trajectory.bursty = true,
                _ => {}
            }
        }
        summary
    }
}

/// Holds the complete result of analysing a single message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisResult {
    pub threat_type: ThreatType,
    pub confidence: Confidence,
    pub action: Action,
    pub score: f32,
    pub explanation: String,
    pub detected_threats: Vec<(ThreatType, f32)>,
    pub signals: Vec<DetectionSignal>,
    pub recommended_action: Option<ActionRecommendation>,
    #[serde(default)]
    pub risk_breakdown: RiskBreakdown,
    #[serde(default)]
    pub contact_snapshot: Option<ContactSnapshot>,
    #[serde(default)]
    pub reason_codes: Vec<String>,
    #[serde(default)]
    pub context_markers: Vec<String>,
    #[serde(default)]
    pub context_summary: AnalysisContextSummary,
    #[serde(default)]
    pub inference: InferenceSummary,
    pub analysis_time_us: u64,
}

impl AnalysisResult {
    /// Creates a clean (no-threat) result with the given analysis duration.
    pub fn clean(analysis_time_us: u64) -> Self {
        Self {
            threat_type: ThreatType::None,
            confidence: Confidence::Low,
            action: Action::Allow,
            score: 0.0,
            explanation: String::new(),
            detected_threats: Vec::new(),
            signals: Vec::new(),
            recommended_action: None,
            risk_breakdown: RiskBreakdown::default(),
            contact_snapshot: None,
            reason_codes: Vec::new(),
            context_markers: Vec::new(),
            context_summary: AnalysisContextSummary::default(),
            inference: InferenceSummary::default(),
            analysis_time_us,
        }
    }

    /// Creates a clean result for a rate-limited message.
    pub fn rate_limited(analysis_time_us: u64) -> Self {
        let mut result = Self::clean(analysis_time_us);
        result.explanation = "rate_limited".to_string();
        result
    }

    /// Returns `true` if any threat was detected.
    pub fn is_threat(&self) -> bool {
        self.threat_type != ThreatType::None
    }

    /// Returns `true` if crisis support resources should be shown to the user.
    pub fn needs_crisis_resources(&self) -> bool {
        self.threat_type == ThreatType::SelfHarm
    }
}

/// Represents the priority level of a parent or guardian alert.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AlertPriority {
    /// No alert required.
    None,
    /// Low-priority informational alert.
    Low,
    /// Medium-priority alert requiring attention.
    Medium,
    /// High-priority alert requiring prompt action.
    High,
    /// Urgent alert requiring immediate action.
    Urgent,
}

/// Represents a recommended follow-up action after a threat is detected.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FollowUpAction {
    /// Continues monitoring the conversation for further signals.
    MonitorConversation,
    /// Suggests blocking the contact to the user.
    BlockSuggested,
    /// Suggests reviewing the contact's full profile.
    ReviewContactProfile,
    /// Recommends reporting the situation to authorities.
    ReportToAuthorities,
}

/// Holds the full set of recommended actions for a detected threat.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActionRecommendation {
    pub parent_alert: AlertPriority,
    pub follow_ups: Vec<FollowUpAction>,
    pub crisis_resources: bool,
    #[serde(default)]
    pub ui_actions: Vec<UiAction>,
    #[serde(default)]
    pub reason_codes: Vec<String>,
}

pub use aura_contracts::ConversationType;

/// Controls detection strictness for enrichment and grooming analysis.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AnalysisMode {
    /// Standard detection thresholds.
    Standard,
    /// Stricter detection thresholds for higher-risk accounts.
    Strict,
}

impl AnalysisMode {
    /// Returns true if this mode uses strict detection thresholds.
    pub fn is_strict(self) -> bool {
        match self {
            AnalysisMode::Standard => false,
            AnalysisMode::Strict => true,
        }
    }
}

/// Represents the media type of a message's content.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContentType {
    /// Plain text message.
    Text,
    /// Image attachment.
    Image,
    /// Voice or audio message.
    Voice,
    /// Video attachment.
    Video,
    /// URL or link-only message.
    Url,
}

/// Holds the raw input data for a single message to be analysed.
#[derive(Debug, Clone)]
pub struct MessageInput {
    pub content_type: ContentType,
    pub text: Option<String>,
    pub image_data: Option<Vec<u8>>,
    pub sender_id: SenderId,
    pub conversation_id: ConversationId,
    pub language: Option<String>,
    pub conversation_type: ConversationType,
    pub member_count: Option<u32>,
    /// Coarse sender relationship metadata supplied by the host application.
    pub sender_relationship: SenderRelationship,
    /// Source used to derive sender_relationship. Self-declared data is not trust.
    pub relationship_trust_source: RelationshipTrustSource,
}
